// <auto-generated />
namespace Zer.Framework.Ef.IntegrationTest.Tests.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addEntity_withstringprimary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addEntity_withstringprimary));
        
        string IMigrationMetadata.Id
        {
            get { return "201708221458190_addEntity_withstringprimary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
