// <auto-generated />
namespace Zer.Framework.Ef.IntegrationTest.Tests.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Init_TestDatas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init_TestDatas));
        
        string IMigrationMetadata.Id
        {
            get { return "201708050722440_Init_TestDatas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
