// <auto-generated />
namespace Zer.GytDataService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modifyPeccanyInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifyPeccanyInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201708120333547_modifyPeccanyInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
