// <auto-generated />
namespace Zer.GytDataService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class lng_add_field_description : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lng_add_field_description));
        
        string IMigrationMetadata.Id
        {
            get { return "201712020906254_lng_add_field_description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
